services:
  garminactivitydownloader:
    image: ghcr.io/c4frf94rdv-crypto/garminactivitydownloader:latest
    container_name: garminactivitydownloader
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - /app/data:/app/data